### ISSUE TITLE
Q: merge/rebase with current bitcoin:master

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#133]
Sort of unrelated to MC and rather shows my lack of knowledge about Git, but let's assume I'd wish to use MasterCore with the current bitcoin:master or some new release. What would be the best way to go?

https://github.com/mastercoin-MSC/mastercore/compare/bitcoin:9d5b5c3a2d273ae8be57592395e0d32bff63c56e...mscore-0.0.8

... shows the difference with an older Bitcoin Core version which should work as filter/mask to roughly estimate only 35 files are added/changed, half of them are tests and only a very few directly involve native files - sure there probably would be some references that might be broken, if bitcoin:master would be used, but I think that's doable.

My question is: what's the best way to do so while keeping commit history intact? Cherry-picking all MC commits would probably work, but I guess there are alternatives?

**Comment by m21** [comment]
There is no easy way Dexx.
35 files changed due to upstream. A ton of MC code is being added in the meantime.
I am being proactively careful not to disrupt much of BTC Core's code due to the above.
Otherwise we are in for major pain, and sometimes 3-way merges.
This is always on my mind and I will rebase it myself when the next official release comes & so on.

**Comment by m21** [comment]
Here I am moving onto 0.9.3 as it was tagged today:
https://github.com/mastercoin-MSC/mastercore/commits/mscore-0.0.9
No commit history is preserved since it's a manual mastercore\* source file copy into this fresh branch.
But next time I think we'll be able to simply rebase this branch to 0.9.4 since now I mscore-0.0.9 is tracking bitcoin/0.9.3 in my local git.

**Comment by dexX7** [comment]
Awesome. Will start testing once it's finished. :)
