### ISSUE TITLE
Unable to sent MP

### ISSUE THREAD

**Issue by firstrow** [mastercoin-MSC/mastercore#305]
Hello. I have a problem in sending money.
Here is the commands I use:

```
$ mastercored getbalance_MP 1BpZdwm2cxvur3J7NVvUJBXM4nJ13bY38w 31                                                                               
{
    "balance" : "4.40496238",
    "reserved" : "0.00000000"
}
```

```
$ mastercored send_MP 1BpZdwm2cxvur3J7NVvUJBXM4nJ13bY38w RECIPIENT_ADDR 31 "4"
error: {"code":-206,"message":"Error with selected inputs for the send transaction"}
```

```
$ mastercored getinfo
{
    "version" : 90300,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 0.02502776,
    "blocks" : 348158,
    "timeoffset" : -2,
    "connections" : 16,
    "proxy" : "",
    "difficulty" : 47427554950.64830017,
    "testnet" : false,
    "keypoololdest" : 1426027641,
    "keypoolsize" : 101,
    "unlocked_until" : 0,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00001000,
    "errors" : ""
}
```

Can anybody help to clarify what going on?
Thanks.

**Comment by dexX7** [comment]
Hey @firstrow,

the issue is that you need some BTC for this transaction, and according to my data, there are only three unspent multisig outputs, worth 0.00000684 BTC each.

Once [5e12e6e48207733e5d71064c90a6238c305fefa55dd1edf5ab16e9d86b8639e5](https://blockchain.info/tx/5e12e6e48207733e5d71064c90a6238c305fefa55dd1edf5ab16e9d86b8639e5) confirmed, you should be good to go.

**Comment by firstrow** [comment]
@dexX7 thank you for the reply. You were right, after transaction was confirmed, I was able to send money. Closing the issue.
